trigger:
  batch: true
  branches:
    include:
      - master
      - release/*

pr:
  batch: true
  branches:
    include:
      - master
      - release/*

pool: Linux

variables:
- name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
  value: 1
- name: BUILD_NUMBER
  value: $[counter('buildnumber', 1)]

steps:
- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: build
    dockerfile: **/Dockerfile

- task: PublishTestResults@2
  displayName: Upload test results
  condition: always()
  continueOnError: true
  inputs:
    testRunner: vstest
    testResultsFiles: '**/*.trx'
